service: log-indexer-lambda
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    OPENSEARCH_ENDPOINT: ${ssm:/log-indexer-lambda/OPENSEARCH_ENDPOINT}
    OPENSEARCH_INDEX: ${ssm:/log-indexer-lambda/OPENSEARCH_INDEX}

package:
  patterns:
    - '!node_modules/aws-sdk/**'
    - '!test/**'
    - '!**/*.test.ts'
    - '!terraform/**'
    - '!*.log'
    - '!docs/**'

functions:
  indexLogs:
    handler: dist/handler.indexLogs
    timeout: 10

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude: ['aws-sdk']
    target: node22
    platform: node

resources:
  Resources:
    AllowCWLogsToInvokeIndexer:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: IndexLogsLambdaFunction
        Action: lambda:InvokeFunction
        Principal: logs.amazonaws.com
        SourceArn: arn:aws:logs:us-east-1:${aws:accountId}:log-group:/aws/lambda/log-generator-lambda-dev-generateLogs:*

    LogGroupSubscriptionFilter:
      Type: AWS::Logs::SubscriptionFilter
      DependsOn:
        - AllowCWLogsToInvokeIndexer
      Properties:
        LogGroupName: /aws/lambda/log-generator-lambda-dev-generateLogs
        FilterPattern: ''
        DestinationArn:
          Fn::GetAtt:
            - IndexLogsLambdaFunction
            - Arn

